# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shivaji Byrapaneni
title: Enterprise Architect
email: shivaji.byrapaneni@gmail.com
website: https://byrash.github.io/

# Social links
# twitter_username: shivaji_io
github_username: byrash
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: shivajib
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Results-driven enterprise architect with a proven track record of delivering high-impact technology solutions that align with business goals. Possesses exceptional technical and strategic planning skills, with an ability to manage complex projects, coordinate stakeholders, and deliver results on time and within budget. Excellent communicator and leader with a strong focus on customer satisfaction.

  
  <mark>
  Enterprise Architecture: Expert in developing enterprise-wide strategies, standards, and processes to align IT with business objectives.
  Technical Knowledge: Proficient in a wide range of technical areas such as cloud computing, networking, database management, security, and software development.
  Project Management: Skilled in leading complex projects, coordinating stakeholders, managing budgets, and delivering results on time and within budget.
  Business Acumen: Strong understanding of business operations and financial management.
  Communication: Excellent communicator with the ability to explain complex technical concepts to non-technical stakeholders, including senior management and executives.
  Leadership: Effective leader with strong interpersonal skills, the ability to motivate and inspire teams, and a track record of success.
  Problem-solving: Skilled in identifying problems, analyzing data, and developing innovative solutions that meet business requirements.
  </mark>  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Motorcycle Rides
   - Bird Watching
   - Walking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
