# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shivaji Byrapaneni
title: Senior Solution Designer / Architect
email: shivaji.byrapaneni@gmail.com
website: https://byrash.github.io/

# Social links
twitter_username: shivaji_io
github_username: byrash
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: shivajib
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Shivaji and I'm a Senior Solution Designer/Architect. I'm experience Polyglot Full Stack Engineer in making software across many bussiness domains. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Solution Designer/Architect \</mark> <mark>Java/J2EE </mark> <mark>Golang</mark> <mark>AWS</mark> and <mark>Most of teh famous SPA Libs & frameworks</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
